# Generated by Django 3.1.7 on 2021-04-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassStrC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passToCheck', models.CharField(max_length=30)),
                ('timeChecked', models.DateTimeField()),
            ],
        ),
    ]
