# Generated by Django 3.1.7 on 2021-04-05 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passstrc',
            name='passstrenght',
            field=models.CharField(default='No password to check', max_length=15),
        ),
    ]
